import { AppShell } from "@/components/layout/app-shell";
import { UserDialog } from "@/components/users/user-dialog";
import { UserStatusButton } from "@/components/users/user-status-button";
import { requireOrganizationAdmin } from "@/lib/auth/require-auth";

type UserRow = { id: string; firebase_uid: string | null; email: string; role: string; status: "active" | "inactive"; employees: { name: string } | { name: string }[] | null; app_user_departments: { departments: { name: string } | { name: string }[] | null }[] };
const roleLabels: Record<string, string> = { sales_rep: "一般ユーザー", department_admin: "部門管理者", organization_admin: "全体管理者" };
export default async function UsersPage() {
  const context = await requireOrganizationAdmin();
  const [{ data: departments }, { data }] = await Promise.all([context.db.from("departments").select("id,name").eq("organization_id", context.organizationId).order("name"), context.db.from("app_users").select("id,firebase_uid,email,role,status,employees(name),app_user_departments(departments(name))").eq("organization_id", context.organizationId).order("created_at")]);
  const users = (data ?? []) as unknown as UserRow[];
  return <AppShell active="/users" displayName={context.displayName} department={context.departmentName}><header className="flex min-h-20 flex-wrap items-center justify-between gap-3 border-b border-slate-200 bg-white px-5 py-4 md:px-8"><div><p className="text-sm text-slate-400">管理</p><h1 className="text-xl font-bold">ユーザー管理</h1></div><UserDialog departments={(departments ?? []) as { id: string; name: string }[]} /></header><div className="mx-auto max-w-6xl p-4 pb-24 md:p-8"><div className="overflow-hidden rounded-2xl border border-slate-200 bg-white">{users.map((user) => { const employee = Array.isArray(user.employees) ? user.employees[0] : user.employees; const relation = user.app_user_departments[0]?.departments; const dept = Array.isArray(relation) ? relation[0] : relation; return <div key={user.id} className="grid items-center gap-3 border-b border-slate-100 p-5 last:border-0 md:grid-cols-[1fr_1.5fr_1fr_1fr_1fr_auto]"><p className="font-semibold">{employee?.name ?? "—"}</p><p className="text-sm text-slate-500">{user.email}</p><p className="text-sm text-slate-500">{dept?.name ?? "—"}</p><p className="text-sm text-slate-500">{roleLabels[user.role] ?? user.role}</p><span className={`w-fit rounded-full px-2.5 py-1 text-xs font-semibold ${user.status === "active" ? "bg-emerald-50 text-emerald-700" : "bg-slate-100 text-slate-500"}`}>{user.status === "active" ? "利用中" : "停止中"}</span>{user.firebase_uid ? <UserStatusButton id={user.id} status={user.status} /> : <span className="text-xs text-amber-600">初回ログイン待ち</span>}</div>; })}</div></div></AppShell>;
}
