import Link from "next/link";
import { notFound } from "next/navigation";
import { updateOpportunity } from "@/app/opportunities/actions";
import { AppShell } from "@/components/layout/app-shell";
import { requireAuth } from "@/lib/auth/require-auth";

type Row = { id: string; name: string; product_name: string | null; stage: string; status: string; confidence: string; priority: string; expected_amount: number; expected_close_date: string | null; notes: string | null };
export default async function EditOpportunityPage({ params }: { params: Promise<{ id: string }> }) {
  const [{ id }, context] = await Promise.all([params, requireAuth()]);
  let query = context.db.from("opportunities").select("id,name,product_name,stage,status,confidence,priority,expected_amount,expected_close_date,notes,employee_id,department_id").eq("organization_id", context.organizationId).eq("id", id);
  if (context.role === "sales_rep") query = query.eq("employee_id", context.employeeId); if (context.role === "department_admin") query = query.in("department_id", context.departmentIds);
  const [{ data }, { data: productRows }] = await Promise.all([query.maybeSingle(), context.db.from("products").select("name").eq("organization_id", context.organizationId).eq("status", "active").order("name")]);
  if (!data) notFound(); const row = data as Row;
  const productOptions = (productRows ?? []).map((item) => [item.name, item.name]);
  if (row.product_name && !productOptions.some(([value]) => value === row.product_name)) productOptions.unshift([row.product_name, `${row.product_name}（現在は無効）`]);
  return <AppShell active="/opportunities" displayName={context.displayName} department={context.departmentName}><main className="mx-auto max-w-3xl p-4 pb-24 md:p-8"><Link href={`/opportunities/${id}`} className="text-sm font-semibold text-slate-500">← 案件詳細へ戻る</Link><form action={updateOpportunity} className="mt-5 rounded-2xl border bg-white p-4 shadow-sm sm:p-6"><h1 className="text-2xl font-bold">案件を編集</h1><input type="hidden" name="id" value={id}/><div className="mt-6 grid gap-5 sm:grid-cols-2"><Field label="案件名" name="name" value={row.name}/><Select label="商材" name="productName" value={row.product_name ?? ""} options={productOptions}/><Select label="商談ステージ" name="stage" value={row.stage} options={[["approach","アプローチ"],["discovery","現状確認"],["proposal","提案"],["closing","クロージング"]]}/><Select label="ステータス" name="status" value={row.status} options={[["open","進行中"],["won","受注"],["lost","失注"],["on_hold","保留"]]}/><Select label="確度" name="confidence" value={row.confidence} options={["A","B","C","D"].map((x) => [x,x])}/><Select label="優先順位" name="priority" value={row.priority} options={[["high","高"],["medium","中"],["low","低"]]}/><Field label="見込金額" name="expectedAmount" value={String(row.expected_amount)} type="number"/><Field label="受注予定日" name="expectedCloseDate" value={row.expected_close_date ?? ""} type="date"/></div><label className="mt-5 block text-sm font-semibold">備考<textarea name="notes" defaultValue={row.notes ?? ""} rows={5} className="mt-2 w-full rounded-xl border p-3 font-normal"/></label><div className="mt-6 flex justify-end"><button className="rounded-xl bg-[#f2c94c] px-6 py-2.5 text-sm font-bold">保存する</button></div></form></main></AppShell>;
}
function Field({ label, name, value, type = "text" }: { label: string; name: string; value: string; type?: string }) { return <label className="text-sm font-semibold">{label}<input required name={name} type={type} defaultValue={value} min={type === "number" ? 0 : undefined} className="mt-2 h-11 w-full rounded-xl border px-3 font-normal"/></label>; }
function Select({ label, name, value, options }: { label: string; name: string; value: string; options: string[][] }) { return <label className="text-sm font-semibold">{label}<select name={name} required defaultValue={value} className="mt-2 h-11 w-full rounded-xl border bg-white px-3 font-normal">{options.map(([optionValue,text]) => <option key={optionValue} value={optionValue}>{text}</option>)}</select></label>; }
