"use client";

import { useActionState, useEffect, useRef } from "react";
import { LoaderCircle, Plus, X } from "lucide-react";
import { useRouter } from "next/navigation";
import { createOpportunity, type OpportunityActionState } from "@/app/opportunities/actions";

const initial: OpportunityActionState = {};
const emptyFields = ["expectedCloseDate", "notes", "branchName", "customerContact", "prefecture", "address", "salesType", "salesProcess", "activityLocation", "activityContact", "activityAttendees", "activityFrom", "activityTo", "vendor", "products", "dealStages", "contractCopy", "detailCopy", "leaseStartDate", "leaseEndDate"];

export function MasterOpportunityDialog({ customers, products, defaultCustomerId }: { customers: { id: string; name: string }[]; products: string[]; defaultCustomerId?: string }) {
  const ref = useRef<HTMLDialogElement>(null); const router = useRouter(); const [state, action, pending] = useActionState(createOpportunity, initial);
  useEffect(() => { if (!state.success) return; ref.current?.close(); if (state.customerExternalId && state.opportunityId) router.push(`/customers/${state.customerExternalId}?opportunityId=${state.opportunityId}`); else router.refresh(); }, [router, state]);
  return <><button type="button" onClick={() => ref.current?.showModal()} className="flex items-center gap-2 rounded-xl bg-[#f2c94c] px-4 py-2.5 text-sm font-bold"><Plus size={18}/>案件を追加</button><dialog ref={ref} className="m-auto w-[min(640px,calc(100%-2rem))] rounded-2xl border border-slate-200 bg-white p-0 shadow-2xl backdrop:bg-slate-950/40"><form action={action} className="p-6"><div className="flex items-start justify-between"><div><p className="text-xs font-bold text-amber-800">案件登録</p><h2 className="mt-1 text-xl font-bold">新しい案件を登録</h2></div><button type="button" onClick={() => ref.current?.close()} aria-label="閉じる"><X size={20}/></button></div><div className="mt-6 grid gap-5 sm:grid-cols-2"><Select name="customerId" label="顧客*" options={customers.map((item) => [item.id,item.name])} value={defaultCustomerId}/><Field name="name" label="案件名*"/><Select name="productName" label="商材*" options={products.map((name) => [name,name])}/></div><input type="hidden" name="stage" value="approach"/><input type="hidden" name="status" value="open"/><input type="hidden" name="confidence" value="B"/><input type="hidden" name="priority" value="medium"/><input type="hidden" name="expectedAmount" value="0"/><input type="hidden" name="customerType" value="corporate"/><input type="hidden" name="teamVisibility" value="department"/><input type="hidden" name="quoteAmount" value="0"/><input type="hidden" name="orderAmount" value="0"/><input type="hidden" name="proposedLeaseFee" value="0"/>{emptyFields.map((name)=><input key={name} type="hidden" name={name} value=""/>)}{state.message && <p className="mt-4 rounded-lg bg-red-50 p-3 text-sm text-red-700">{state.message}</p>}<div className="mt-6 flex justify-end"><button disabled={pending || products.length === 0} className="flex items-center gap-2 rounded-xl bg-[#f2c94c] px-5 py-2.5 text-sm font-bold disabled:opacity-50">{pending && <LoaderCircle size={17} className="animate-spin"/>}登録する</button></div></form></dialog></>;
}
function Field({ name, label }: { name: string; label: string }) { return <label className="text-sm font-semibold">{label}<input name={name} required className="mt-2 h-11 w-full rounded-xl border px-3 font-normal"/></label>; }
function Select({ name, label, options, value }: { name: string; label: string; options: string[][]; value?: string }) { return <label className="text-sm font-semibold">{label}<select name={name} required defaultValue={value ?? ""} className="mt-2 h-11 w-full rounded-xl border bg-white px-3 font-normal"><option value="">選択してください</option>{options.map(([id,text])=><option key={id} value={id}>{text}</option>)}</select></label>; }
