import { Search, X } from "lucide-react";
import Link from "next/link";
export type OpportunitySearchValues=Record<string,string|string[]|undefined>;
const products=["ホームテレホン","ビジネスフォン","FAX","複合機","UTM","サーバー","ネットワーク商材","防犯カメラ","AXCEL","コラボ","LED","UPS・SSW・ルーター","その他"];
const vendors=["局","メディア","日通器","電通","トップ","OAセンター","OA通信","レイズ","オフィス24","その他"];
const prefs=["北海道","青森県","岩手県","宮城県","秋田県","山形県","福島県","茨城県","栃木県","群馬県","埼玉県","千葉県","東京都","神奈川県","新潟県","富山県","石川県","福井県","山梨県","長野県","岐阜県","静岡県","愛知県","三重県","滋賀県","京都府","大阪府","兵庫県","奈良県","和歌山県","鳥取県","島根県","岡山県","広島県","山口県","徳島県","香川県","愛媛県","高知県","福岡県","佐賀県","長崎県","熊本県","大分県","宮崎県","鹿児島県","沖縄県"];
export function OpportunitySearchForm({values,members,departments=[]}:{values:OpportunitySearchValues;members:{id:string;name:string}[];departments?:{id:string;name:string}[]}){
 const v=(n:string)=>typeof values[n]==="string"?values[n] as string:""; const vs=(n:string)=>Array.isArray(values[n])?values[n] as string[]:values[n]?[values[n] as string]:[];
 const searched=v("searched")==="1";
 return <form className="mb-6 overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm">
  <input type="hidden" name="searched" value="1"/>
  <details open={searched}>
  <summary className="flex cursor-pointer list-none items-center justify-between px-5 py-4 marker:content-none hover:bg-slate-50"><span className="font-bold">絞り込み条件を開く</span>{searched&&<span className="text-xs font-semibold text-slate-400">条件を適用中 ▲</span>}</summary>
  <div className="flex items-center justify-between border-y bg-slate-50 px-5 py-3"><h2 className="font-bold">検索条件</h2><span className="text-xs text-slate-400">旧SFAの検索項目に対応</span></div>
  <div className="space-y-7 p-5 md:p-6">
   <Section title="表示条件"><div className="grid gap-4 lg:grid-cols-2">
    <Choices label="表示する顧客"><Check n="customerTypes" val="corporate" label="法人・団体顧客" on={vs("customerTypes").includes("corporate")}/><Check n="customerTypes" val="individual" label="個人顧客" on={vs("customerTypes").includes("individual")}/><Check n="includeFamily" val="true" label="家族情報を含む" on={v("includeFamily")==="true"}/></Choices>
    <Choices label="活動の表示方法"><Radio n="activityDisplay" val="perOpportunity" label="案件毎に表示する" on={!v("activityDisplay")||v("activityDisplay")==="perOpportunity"}/><Radio n="activityDisplay" val="latest" label="最終活動のみ表示する" on={v("activityDisplay")==="latest"}/><Radio n="activityDisplay" val="all" label="すべての活動を表示する" on={v("activityDisplay")==="all"}/></Choices>
   </div><Grid><Choices label="営業担当範囲"><Radio n="salesScope" val="department" label="部署" on={v("salesScope")==="department"}/><Radio n="salesScope" val="team" label="チーム" on={!v("salesScope")||v("salesScope")==="team"}/></Choices><Select label="営業担当 部署・チーム" n="salesDepartment" value={v("salesDepartment")} options={departments.map(x=>[x.id,x.name])} empty="すべて"/><Select label="営業担当" n="owner" value={v("owner")} options={members.map(x=>[x.id,x.name])}/></Grid></Section>
   <Section title="案件情報"><Grid><Field label="顧客名" n="customer" value={v("customer")}/><Field label="拠点名" n="branch" value={v("branch")}/><Field label="顧客担当者" n="customerContact" value={v("customerContact")}/><Select label="顧客拠点／個人顧客所在 都道府県" n="prefecture" value={v("prefecture")} options={prefs.map(x=>[x,x])}/><Field label="住所" n="address" value={v("address")}/><Field label="案件名" n="q" value={v("q")}/><Select label="商材" n="product" value={v("product")} options={products.map(x=>[x,x])}/><Select label="案件状態" n="status" value={v("status")} options={[["open","進行中"],["won","受注"],["lost","失注"],["on_hold","保留"]]}/></Grid></Section>
   <Section title="活動情報"><Grid><Select label="営業タイプ" n="salesType" value={v("salesType")} options={[["IT営業活動","IT営業活動"],["フォロー","フォロー"],["書類不備","書類不備"]]}/><Select label="営業プロセス" n="salesProcess" value={v("salesProcess")} options={[["IT営業活動","IT営業活動"],["IT同行活動","IT同行活動"]]}/><Select label="活動時点" n="activityTiming" value={v("activityTiming")} options={[["before","以前"],["same","同日"],["after","以後"]]} empty="以前"/><Field label="活動拠点" n="activityLocation" value={v("activityLocation")}/><Field label="顧客面談者" n="activityContact" value={v("activityContact")}/><Field label="活動同席者" n="attendees" value={v("attendees")}/><Range label="期間指定" a="activityFrom" b="activityTo" av={v("activityFrom")} bv={v("activityTo")} type="date"/><Threshold label="確度" n="confidence" value={v("confidence")} op="confidenceOperator" opv={v("confidenceOperator")} options={[["A","A：高"],["B","B：普通"],["C","C：低"],["D","D：未確定"]]}/><Threshold label="優先順位" n="priority" value={v("priority")} op="priorityOperator" opv={v("priorityOperator")} options={[["high","高"],["medium","中"],["low","低"]]}/><Range label="見積額" a="quoteMin" b="quoteMax" av={v("quoteMin")} bv={v("quoteMax")} type="number"/><Range label="受注額" a="orderMin" b="orderMax" av={v("orderMin")} bv={v("orderMax")} type="number"/><Choices label="個別活動担当範囲"><Radio n="activityOwnerScope" val="department" label="部署" on={v("activityOwnerScope")==="department"}/><Radio n="activityOwnerScope" val="team" label="チーム" on={!v("activityOwnerScope")||v("activityOwnerScope")==="team"}/></Choices><Select label="個別活動担当 部署・チーム" n="activityDepartment" value={v("activityDepartment")} options={departments.map(x=>[x.id,x.name])} empty="すべて"/><Select label="個別活動担当" n="activityOwner" value={v("activityOwner")} options={members.map(x=>[x.id,x.name])}/></Grid></Section>
   <Section title="カスタム検索"><Grid><Field label="販社（部分一致検索）" n="vendor" value={v("vendor")}/><Range label="受注予定日" a="closeFrom" b="closeTo" av={v("closeFrom")} bv={v("closeTo")} type="date"/><Range label="提案リース料金" a="leaseFeeMin" b="leaseFeeMax" av={v("leaseFeeMin")} bv={v("leaseFeeMax")} type="number"/><Multi label="商品" n="products" values={vs("products")} options={products}/><Checks label="商談ステージ" n="stages" values={vs("stages")} options={[["approach","アプローチ"],["discovery","現状確認"],["proposal","提案"],["closing","クロージング"]]}/><Multi label="販社" n="vendors" values={vs("vendors")} options={vendors}/><Multi label="契約書コピー" n="contractCopies" values={vs("contractCopies")} options={["◎","×"]}/><Multi label="明細コピー" n="detailCopies" values={vs("detailCopies")} options={["◎","×"]}/><Range label="リース開始年月日" a="leaseStartFrom" b="leaseStartTo" av={v("leaseStartFrom")} bv={v("leaseStartTo")} type="date"/><Range label="リース終了年月日" a="leaseEndFrom" b="leaseEndTo" av={v("leaseEndFrom")} bv={v("leaseEndTo")} type="date"/></Grid></Section>
  </div><div className="sticky bottom-0 flex justify-end gap-2 border-t bg-white/95 px-5 py-4 backdrop-blur"><Link href="/opportunities" className="flex items-center gap-2 rounded-xl border px-4 py-2.5 text-sm font-bold text-slate-500"><X size={16}/>クリア</Link><button className="flex items-center gap-2 rounded-xl bg-[#f2c94c] px-6 py-2.5 text-sm font-bold hover:bg-[#e5ad00]"><Search size={17}/>検索する</button></div>
  </details>
 </form>
}
function Section({title,children}:{title:string;children:React.ReactNode}){return <section className="space-y-4"><h3 className="border-l-4 border-[#e5ad00] pl-3 text-sm font-bold">{title}</h3>{children}</section>}
function Grid({children}:{children:React.ReactNode}){return <div className="grid gap-4 md:grid-cols-2 xl:grid-cols-4">{children}</div>}
function Field({label,n,value}:{label:string;n:string;value:string}){return <label className="text-xs font-semibold text-slate-500">{label}<input name={n} defaultValue={value} className="mt-1.5 h-10 w-full rounded-lg border px-3 text-sm outline-none focus:border-amber-500"/></label>}
function Select({label,n,value,options,empty="選択なし"}:{label:string;n:string;value:string;options:string[][];empty?:string}){return <label className="text-xs font-semibold text-slate-500">{label}<select name={n} defaultValue={value} className="mt-1.5 h-10 w-full rounded-lg border bg-white px-3 text-sm"><option value="">{empty}</option>{options.map(([a,b])=><option key={a} value={a}>{b}</option>)}</select></label>}
function Range({label,a,b,av,bv,type}:{label:string;a:string;b:string;av:string;bv:string;type:string}){return <div className="text-xs font-semibold text-slate-500">{label}<div className="mt-1.5 flex items-center gap-2"><input name={a} type={type} defaultValue={av} min={type==="number"?0:undefined} className="h-10 min-w-0 flex-1 rounded-lg border px-2 text-sm font-normal"/><span>～</span><input name={b} type={type} defaultValue={bv} min={type==="number"?0:undefined} className="h-10 min-w-0 flex-1 rounded-lg border px-2 text-sm font-normal"/></div></div>}
function Choices({label,children}:{label:string;children:React.ReactNode}){return <fieldset className="rounded-lg border px-3 py-2"><legend className="px-1 text-xs font-semibold text-slate-500">{label}</legend><div className="flex flex-wrap gap-3 text-sm">{children}</div></fieldset>}
function Radio({n,val,label,on}:{n:string;val:string;label:string;on:boolean}){return <label className="flex items-center gap-1.5"><input type="radio" name={n} value={val} defaultChecked={on} className="accent-amber-500"/>{label}</label>}
function Check({n,val,label,on}:{n:string;val:string;label:string;on:boolean}){return <label className="flex items-center gap-1.5"><input type="checkbox" name={n} value={val} defaultChecked={on} className="accent-amber-500"/>{label}</label>}
function Threshold({label,n,value,op,opv,options}:{label:string;n:string;value:string;op:string;opv:string;options:string[][]}){return <div className="text-xs font-semibold text-slate-500">{label}<div className="mt-1.5 flex gap-2"><select name={n} defaultValue={value} className="h-10 min-w-0 flex-1 rounded-lg border bg-white px-2 text-sm"><option value="">選択なし</option>{options.map(([a,b])=><option key={a} value={a}>{b}</option>)}</select><select name={op} defaultValue={opv||"lte"} className="h-10 rounded-lg border bg-white px-2 text-sm"><option value="lte">以下</option><option value="gte">以上</option></select></div></div>}
function Multi({label,n,values,options}:{label:string;n:string;values:string[];options:string[]}){return <CompactMulti label={label} n={n} values={values} options={options.map(x=>[x,x])}/>}
function Checks({label,n,values,options}:{label:string;n:string;values:string[];options:string[][]}){return <CompactMulti label={label} n={n} values={values} options={options}/>}
function CompactMulti({label,n,values,options}:{label:string;n:string;values:string[];options:string[][]}){const summary=values.length===0?"選択なし":values.length===1?(options.find(([value])=>value===values[0])?.[1]??values[0]):`${values.length}件選択中`;return <div className="text-xs font-semibold text-slate-500"><span>{label}</span><details className="group relative mt-1.5"><summary className="flex h-10 cursor-pointer list-none items-center justify-between rounded-lg border border-slate-200 bg-white px-3 text-sm font-normal text-slate-700 marker:content-none hover:border-amber-400"><span className="truncate">{summary}</span><span className="ml-2 text-[10px] text-slate-400 transition group-open:rotate-180">▼</span></summary><div className="absolute z-20 mt-1 max-h-64 w-full min-w-52 overflow-y-auto rounded-xl border border-slate-200 bg-white p-2 shadow-xl">{options.map(([value,text])=><label key={value} className="flex cursor-pointer items-center gap-2 rounded-lg px-2.5 py-2 text-sm font-normal text-slate-700 hover:bg-amber-50"><input type="checkbox" name={n} value={value} defaultChecked={values.includes(value)} className="size-4 accent-amber-500"/><span>{text}</span></label>)}</div></details></div>}
