import { ArrowLeft } from "lucide-react";
import Link from "next/link";
import { notFound } from "next/navigation";
import { ActivityMemoForm } from "@/components/activities/activity-memo-form";
import { AppShell } from "@/components/layout/app-shell";
import { requireAuth } from "@/lib/auth/require-auth";
type Row = { starts_at: string; ends_at: string; department_id: string; customers: { name: string } | { name: string }[] | null };
export default async function ActivityMemoPage({ params }: { params: Promise<{ id: string }> }) { const [{ id }, context] = await Promise.all([params, requireAuth()]); let request = context.db.from("activities").select("starts_at,ends_at,department_id,employee_id,customers(name)").eq("organization_id", context.organizationId).eq("id", id); if (context.role === "sales_rep") request = request.eq("employee_id", context.employeeId); if (context.role === "department_admin") request = request.in("department_id", context.departmentIds); const { data } = await request.maybeSingle(); if (!data) notFound(); const row = data as unknown as Row; let departmentRequest = context.db.from("departments").select("id,name").eq("organization_id", context.organizationId).order("name"); if (context.role !== "organization_admin") departmentRequest = departmentRequest.in("id", context.departmentIds); const { data: departments } = await departmentRequest; const relation = row.customers; const customerName = (Array.isArray(relation) ? relation[0]?.name : relation?.name) ?? ""; return <AppShell active="/results" displayName={context.displayName} department={context.departmentName}><div className="mx-auto max-w-3xl p-4 pb-24 md:p-8"><Link href="/" className="mb-5 inline-flex items-center gap-2 text-sm font-semibold text-slate-500"><ArrowLeft size={17} />カレンダーへ戻る</Link><section className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm md:p-8"><p className="text-xs font-bold text-amber-800">活動メモ</p><h1 className="mb-6 mt-1 text-2xl font-bold">活動メモを新規登録</h1><ActivityMemoForm departments={(departments ?? []) as { id: string; name: string }[]} defaultDepartmentId={row.department_id} customerName={customerName} date={tokyoDate(row.starts_at)} startTime={tokyoTime(row.starts_at)} endTime={tokyoTime(row.ends_at)} /></section></div></AppShell>; }
function tokyoDate(value: string) { return new Intl.DateTimeFormat("en-CA", { timeZone: "Asia/Tokyo", year: "numeric", month: "2-digit", day: "2-digit" }).format(new Date(value)); }
function tokyoTime(value: string) { return new Intl.DateTimeFormat("ja-JP", { timeZone: "Asia/Tokyo", hour: "2-digit", minute: "2-digit", hour12: false }).format(new Date(value)); }
