"use client";
import { useActionState } from "react";
import { LoaderCircle } from "lucide-react";
import { createActivityMemo, type CreateActivityState } from "@/app/activities/actions";
type DepartmentOption = { id: string; name: string };
export function ActivityMemoForm({ departments, defaultDepartmentId, customerName, date, startTime, endTime }: { departments: DepartmentOption[]; defaultDepartmentId: string; customerName: string; date: string; startTime: string; endTime: string }) {
  const [state, action, pending] = useActionState(createActivityMemo, {} as CreateActivityState);
  return <form action={action} className="space-y-5"><label className="block text-sm font-semibold">顧客名<input name="customerName" defaultValue={customerName} required className="mt-2 h-11 w-full rounded-xl border border-slate-200 px-3 font-normal outline-none focus:border-amber-500" /></label><div className="grid gap-4 sm:grid-cols-2"><label className="block text-sm font-semibold">担当部門<select name="departmentId" defaultValue={defaultDepartmentId} required className="mt-2 h-11 w-full rounded-xl border border-slate-200 bg-white px-3 font-normal">{departments.map((d) => <option key={d.id} value={d.id}>{d.name}</option>)}</select></label><label className="block text-sm font-semibold">活動日<input name="date" type="date" defaultValue={date} required className="mt-2 h-11 w-full rounded-xl border border-slate-200 px-3 font-normal" /></label></div><div className="grid grid-cols-2 gap-4"><label className="block text-sm font-semibold">開始<input name="startTime" type="time" defaultValue={startTime} required className="mt-2 h-11 w-full rounded-xl border border-slate-200 px-3 font-normal" /></label><label className="block text-sm font-semibold">終了<input name="endTime" type="time" defaultValue={endTime} required className="mt-2 h-11 w-full rounded-xl border border-slate-200 px-3 font-normal" /></label></div><label className="block text-sm font-semibold">活動詳細<textarea name="details" required rows={10} className="mt-2 w-full rounded-xl border border-slate-200 p-3 font-normal leading-6 outline-none focus:border-amber-500" /></label>{state.message && <p className="rounded-lg bg-red-50 p-3 text-sm text-red-700">{state.message}</p>}<div className="flex justify-end"><button disabled={pending} className="flex min-w-28 items-center justify-center gap-2 rounded-xl bg-[#f2c94c] px-5 py-3 text-sm font-bold text-slate-900 disabled:opacity-50">{pending && <LoaderCircle size={17} className="animate-spin" />}{pending ? "登録中" : "メモを登録"}</button></div></form>;
}
