"use client";

import { useActionState, useState } from "react";
import { CheckCircle2, FileAudio, LoaderCircle } from "lucide-react";
import { saveDetailedActivityReport, type DetailedReportState } from "@/app/activities/[id]/report/actions";
import { defaultProductNames } from "@/domain/products/defaults";

type Member = { id: string; name: string };
type Defaults = { date: string; startTime: string; endTime: string; product: string; ownerId: string; progressStep: string; salesType: string; activityStatus: string; nextVisitDate: string; nextActionDetails: string; details: string; aiSummary: string };

const salesProcesses: Record<string, string[]> = {
  "IT営業活動": ["IT営業活動"], "IT営業外活動": ["書類不備", "工事立会", "納品", "フォロー"], "IT同行活動": ["IT同行活動"],
  "CS営業活動": ["CS営業活動"], "CS営業外活動": ["CS営業外活動"], "アルファサポート": ["アルファサポート"],
  "AXCEL定期訪問": ["AXCEL"], "AXCEL不定期訪問": ["AXCEL"],
};
const statuses = ["提案中", "受注", "失注", "保留中"];
const ranks = ["A", "B", "C", "D", "E"];

export function ActivityReportForm({ activityId, defaults, members, activityOwners }: { activityId: string; defaults: Defaults; members: Member[]; activityOwners: Member[] }) {
  const [state, action, pending] = useActionState(saveDetailedActivityReport, {} as DetailedReportState);
  const [salesType, setSalesType] = useState(salesProcesses[defaults.salesType] ? defaults.salesType : "IT営業活動");
  const [status, setStatus] = useState(statuses.includes(defaults.activityStatus) ? defaults.activityStatus : "提案中");
  const [registrationType, setRegistrationType] = useState<"actual" | "planned">("actual");
  const processOptions = salesProcesses[salesType];
  const isItSales = salesType === "IT営業活動";
  const isAxcel = salesType.startsWith("AXCEL");

  return <form action={action} className="space-y-5"><input type="hidden" name="id" value={activityId}/>
    <Section title="登録内容の選択"><div className="flex flex-wrap gap-5"><label className="inline-flex items-center gap-2 text-sm"><input type="radio" name="registrationType" value="actual" checked={registrationType === "actual"} onChange={() => setRegistrationType("actual")} className="size-4 accent-amber-500"/>活動実績を登録する（共通活動／個別活動）</label><label className="inline-flex items-center gap-2 text-sm"><input type="radio" name="registrationType" value="planned" checked={registrationType === "planned"} onChange={() => setRegistrationType("planned")} className="size-4 accent-amber-500"/>活動予定を登録する（活動予定のみ）</label></div></Section>
    <Section title={registrationType === "actual" ? "共通活動" : "活動予定"} description="営業タイプとステータスに応じて、必要な項目が切り替わります。"><Grid>
      <Select name="salesType" label="営業タイプ" options={Object.keys(salesProcesses)} defaultValue={salesType} required onChange={setSalesType}/>
      <Select key={salesType} name="salesProcess" label="営業プロセス" options={processOptions} defaultValue={processOptions[0]} required/>
      <Select name="activityStatus" label="ステータス" options={statuses} defaultValue={status} required onChange={setStatus}/>
      <Field name="activityDate" label="活動日" value={defaults.date} type="date" required/>
      {salesType === "IT同行活動" && <Select name="activityLocation" label="活動拠点" options={["本社"]} defaultValue="本社" required/>}
      <div className="sm:col-span-2"><ProductEditor initialProduct={defaults.product} status={status} showQuantity={isItSales || salesType === "IT同行活動"}/></div><Field name="customerContact" label="面談者"/>
      <MemberChecks name="attendeeEmployeeIds" label="同席者" members={members}/>
      {salesType === "IT同行活動" && <Select name="priority" label="優先順位" options={["Ａ 緊急", "Ｂ 高", "Ｃ 普通", "Ｄ 低"]} defaultValue="Ｃ 普通" required/>}
      <Select name="confidence" label="確度" options={["Ａ：高い", "Ｂ：普通", "Ｃ：低い"]} defaultValue="Ｂ：普通" required/>
      {(isItSales || isAxcel) && status === "提案中" && <Field name="nextVisitDate" label="次回訪問予定日" value={defaults.nextVisitDate} type="date" required={isItSales}/>}
      {salesType === "AXCEL定期訪問" && <MonthFields/>}
      {status === "失注" && salesType === "IT同行活動" && <Select name="lossReason" label="失注理由" options={["時期", "競合", "機能", "価格", "その他"]} required/>}
      {status === "失注" && isAxcel && <Field name="lossReason" label="失注理由"/>}{status === "保留中" && isAxcel && <Field name="holdReason" label="保留理由"/>}
      {isItSales && <div className="sm:col-span-2"><Field name="progressStep" label="進行工程" value={defaults.progressStep} placeholder="例：提案準備、実施中、確認待ち"/></div>}
      {["IT同行活動", "AXCEL定期訪問", "AXCEL不定期訪問"].includes(salesType) && <div className="sm:col-span-2"><Area name="commonNotes" label="備考" rows={4}/></div>}
    </Grid>
      {isItSales && <Rows><Choice label="コラボ提案" name="collaborationProposal" options={["提案あり", "提案なし"]} required/><Choice label="電気提案" name="electricityProposal" options={["提案あり", "提案なし"]} required/><Choice label="商談変化" name="dealChange" options={["○", "△", "×", "△=>○", "△=>×"]} defaultValue="△" required/><Checks label="提案商材" name="proposedProducts" options={["UTM", "スイッチ", "AP", "複合機", "電話機", "サーバー", "その他"]} required/>{status === "提案中" && <Area name="nextActionDetails" label="次回アクション内容" rows={4} value={defaults.nextActionDetails} required/>}<Choice label="AXCEL同時提案" name="axcelProposal" options={["あり", "なし", "加入済"]} required/><Choice label="AXCEL提案内容" name="axcelProposalDetail" options={["DX＊きづな 訴求あり合意", "DX＊きづな 訴求あり・未合意", "DX＊きづな 訴求なし"]} required/><Checks label="AXCELプレゼン内容" name="axcelPresentation" options={["5大資源ツール説明", "申込チェック説明あり", "申込チェック説明なし"]}/></Rows>}
      {["IT営業活動", "CS営業活動", "CS営業外活動", "アルファサポート"].includes(salesType) && <Choice label="顧客属性" name="customerAttribute" options={["ユーザーAXCELなし", "新規", "ユーザーAXCELあり", "ユーザー（AXCEL解約履歴あり）"]} required/>}
      {salesType !== "アルファサポート" && <Choice label="面談者（区分）" name="contactRole" options={["決裁者", "準決裁者", "担当者"]} required/>}
      {isItSales && status !== "提案中" && <Field name="followUpVisitDate" label="次回訪問予定" value={defaults.nextVisitDate} type="date"/>}
      {isItSales && status === "受注" && <><Select name="oaOrderReason" label="OA受注理由" options={["経費削減", "新設・移設・増設などのタイミング", "保守一元化", "商品機能メリット", "信用獲得", "業務効率改善", "バンドル受注"]} required/><Select name="axcelOrderReason" label="AXCEL受注理由" options={["バンドル受注", "売上拡大", "業務効率改善", "保守一元化", "AXCEL受注無し"]} required/><Select name="axcelLossDetail" label="AXCEL失注内容" options={axcelLossOptions} required/></>}
      {isItSales && status === "失注" && <><Select name="axcelOrderReason" label="AXCEL受注理由" options={["バンドル受注", "売上拡大", "業務効率改善", "保守一元化", "AXCEL受注無し"]} required/><Select name="oaLossDetail" label="OA失注内容" options={["料金アウト", "再リースアウト", "販売店アウト", "局アウト", "延長アウト", "ファッションアウト", "まだあるアウト", "時期NG"]} required/><Select name="axcelLossDetail" label="AXCEL失注内容" options={axcelLossOptions} required/></>}
    </Section>
    <Section title={registrationType === "actual" ? "個別情報" : "活動予定の詳細"} description="活動担当者は社員マスタから選択します。ログインアカウントの有無とは別管理です。"><Grid>
      <MemberSelect name="activityOwnerId" label="活動担当者" members={activityOwners} defaultValue={defaults.ownerId} required/><TimeRange start={defaults.startTime} end={defaults.endTime}/>{registrationType === "actual" && <div className="sm:col-span-2"><AiDetailsArea initialDetails={defaults.details} aiSummary={defaults.aiSummary}/></div>}
      {isItSales && <><Choice label="訪問回数" name="visitCount" options={["初回訪問", "再訪問", "3回目", "4回目以降"]} required/><MemberSelect name="appointmentOwnerId" label="アポ担当" members={members} extraOptions={staffExtras}/><MemberSelect name="fieldOwnerId" label="現場担当" members={members} extraOptions={staffExtras}/><MemberSelect name="companionOwnerId" label="同行担当" members={members} extraOptions={staffExtras}/><Select name="appointmentType" label="アポ内容" options={["新規アポ", "GUP", "他商材", "増設", "コラボ", "AXCEL", "直訪", "その他"]}/><Field name="negotiator" label="商談担当者"/><Field name="negotiatorTitle" label="商談担当者役職"/><Choice label="商談ステージ" name="dealStage" options={["アプローチ", "現状確認", "提案", "クロージング"]}/><Field name="vendor" label="販社"/><Field name="model" label="機種"/><Field name="proposedModel" label="提案機種"/><Field name="currentLeaseCompany" label="現在リース会社"/><Field name="leaseCompany" label="リース会社"/><Field name="currentLeaseFee" label="現在リース料金" type="number"/><Field name="proposedLeaseFee" label="提案リース料金" type="number"/><Field name="remainingLeasePayments" label="リース残回数" type="number"/><Select name="pricingSetting" label="料金設定" options={["料金UP", "料金DOWN", "等価"]}/></>}
      {salesType === "CS営業活動" && <><Select name="csCustomerRank" label="CS顧客ランク" options={ranks}/><Select name="itCustomerRank" label="IT顧客ランク" options={ranks}/><Field name="stayMinutes" label="滞在時間（分）" type="number" required/><Field name="returnTime" label="帰社時刻" type="time"/><Field name="respondent" label="応対者様"/><Select name="vehicle" label="車種" options={vehicles}/><Select name="csActivityContent" label="活動内容" options={["清掃活動", "PR活動", "チラシお渡し"]}/><div className="sm:col-span-2"><Area name="episode" label="エピソード" rows={4}/></div></>}
      {salesType === "CS営業外活動" && <><Select name="csNonSalesActivity" label="CS営業外活動" options={["処理", "物品納入", "設定関係"]}/><Field name="stayMinutes" label="滞在時間（分）" type="number" required/></>}
      {salesType === "アルファサポート" && <><Field name="plannedStayMinutes" label="滞在予定時間（分）" type="number"/><Field name="stayMinutes" label="滞在時間（分）" type="number"/><Field name="returnTime" label="帰社時刻" type="time"/><Select name="vehicle" label="車種" options={vehicles}/><Select name="constructionContent" label="工事内容" options={["機器工事", "回線工事", "下見", "打合せ", "障害（代替え有り）", "障害（代替え無し）", "先行配線", "移転", "設定"]}/><Select name="constructionProgress" label="工事進捗" options={["完了", "残工事", "次回工事", "延期", "キャンセル"]}/></>}
      {salesType === "AXCEL定期訪問" && <><Choice label="宿題獲得" name="homeworkAcquired" options={["あり", "なし"]} allowEmpty required/><Field name="homeworkDetails" label="宿題内容"/><Choice label="次回アポ" name="nextAppointment" options={["あり", "なし"]} allowEmpty required/><Checks label="効果測定項目" name="effectMeasurementItems" options={["RMの課題一覧", "アイコンカルテ", "GXレポート", "WEB", "導入商材", "なし"]} required/><Choice label="トス出し" name="referral" options={["あり", "なし"]} allowEmpty required/><Field name="stayMinutes" label="滞在時間（分）" type="number" required/><Field name="travelMinutes" label="移動時間（分）" type="number" required/>{status === "提案中" && <Choice label="リモート" name="remote" options={["あり", "なし"]} allowEmpty required/>}</>}
      {salesType === "AXCEL不定期訪問" && <><Select name="axcelIrregularActivity" label="AXCEL不定期訪問" options={["障害対応", "クレーム対応", "工事立ち合い", "同行", "顔出し訪問", "アシスト"]} required/><Field name="stayMinutes" label="滞在時間（分）" type="number" required/><Field name="travelMinutes" label="移動時間（分）" type="number" required/></>}
      {["IT営業外活動", "IT同行活動"].includes(salesType) && <Field name="stayMinutes" label="滞在時間（分）" type="number" required/>}
    </Grid></Section>
    <Section title="AI商談分析" description="文字起こし済みの商談テキストを貼り付けると、活動登録後に話者分離と詳細分析を行います。"><input type="hidden" name="audioPath" value=""/><input type="hidden" name="audioContentType" value=""/><label className="block text-xs font-bold text-slate-600">商談・通話の文字起こし<textarea name="aiTranscript" rows={12} placeholder="文字起こし済みの全文を、そのまま貼り付けてください。" className="mt-1.5 w-full rounded-xl border border-slate-200 p-3 text-sm font-normal leading-7 outline-none focus:border-amber-500"/></label><div className="flex items-start gap-3 rounded-xl border border-dashed border-slate-300 bg-slate-50 px-4 py-4 text-slate-500"><FileAudio size={20} className="mt-0.5 shrink-0"/><div><p className="text-sm font-bold text-slate-700">音声アップロードは準備中です</p><p className="mt-1 text-xs leading-6">現在は文字起こし済みテキストをご利用ください。</p></div></div></Section>
    {state.message && !state.success && <p className="rounded-lg bg-red-50 p-3 text-sm text-red-700">{state.message}</p>}{state.success && <p className="flex items-center gap-2 rounded-lg bg-emerald-50 p-3 text-sm font-semibold text-emerald-700"><CheckCircle2 size={18}/>{state.message}</p>}
    <div className="flex justify-end border-t border-slate-200 pt-5"><button disabled={pending || state.success} className="flex min-w-40 items-center justify-center gap-2 rounded-xl bg-[#f2c94c] px-5 py-3 text-sm font-bold text-slate-900 disabled:opacity-50">{pending && <LoaderCircle size={18} className="animate-spin"/>}{pending ? "保存中" : "活動を登録する"}</button></div>
  </form>;
}

const axcelLossOptions = ["受注有 理由不要", "商談相手が決裁者でない", "意識的に話さなかった", "話せなかった", "移転予定", "業者指定", "経営状態", "コストアップ", "時期NG", "廃業予定", "その他"];
const vehicles = ["カムリ", "IQ", "アクアみ532", "アクアに532", "アクアな532", "プリウスせ334", "プリウスに333", "スイフト", "プリウスら333", "プリウスも333", "イグニスな533", "イグニスと533", "ミライース", "フィットろ532", "イグニスぬ533", "モコ", "プリウスα", "代車"];
const productOptions = [...defaultProductNames];
const staffExtras = [{ id: "external", name: "外部" }, { id: "ntt", name: "NTT" }, { id: "manufacturer", name: "メーカー" }];
const input = "mt-1.5 h-11 w-full rounded-xl border border-slate-200 bg-white px-3 text-sm font-normal outline-none focus:border-amber-500";
function Required() { return <span className="ml-1 text-red-500">★</span>; }
function Section({ title, description, children }: { title: string; description?: string; children: React.ReactNode }) { return <section className="overflow-hidden rounded-xl border border-slate-200"><div className="border-b border-slate-200 bg-slate-50 px-4 py-3"><h2 className="text-sm font-bold">{title}</h2>{description && <p className="mt-1 text-xs text-slate-400">{description}</p>}</div><div className="space-y-5 p-4 md:p-5">{children}</div></section>; }
function Grid({ children }: { children: React.ReactNode }) { return <div className="grid gap-4 sm:grid-cols-2">{children}</div>; } function Rows({ children }: { children: React.ReactNode }) { return <div className="divide-y divide-slate-100">{children}</div>; }
function Field({ name, label, value, type = "text", placeholder, required }: { name: string; label: string; value?: string; type?: string; placeholder?: string; required?: boolean }) { return <label className="text-xs font-bold text-slate-500">{label}{required && <Required/>}<input name={name} type={type} min={type === "number" ? 0 : undefined} defaultValue={value} placeholder={placeholder} required={required} className={input}/></label>; }
function Area({ name, label, rows, value, required }: { name: string; label: string; rows: number; value?: string; required?: boolean }) { return <label className="block text-xs font-bold text-slate-500">{label}{required && <Required/>}<textarea name={name} rows={rows} defaultValue={value} required={required} className="mt-1.5 w-full rounded-xl border border-slate-200 p-3 text-sm font-normal outline-none focus:border-amber-500"/></label>; }
function Select({ name, label, options, defaultValue, required, onChange }: { name: string; label: string; options: string[]; defaultValue?: string; required?: boolean; onChange?: (value: string) => void }) { return <label className="text-xs font-bold text-slate-500">{label}{required && <Required/>}<select name={name} defaultValue={defaultValue ?? ""} required={required} onChange={onChange ? (event) => onChange(event.target.value) : undefined} className={input}><option value="">選択してください</option>{options.map((item) => <option key={item}>{item}</option>)}</select></label>; }
function Choice({ label, name, options, defaultValue, required, allowEmpty }: { label: string; name: string; options: string[]; defaultValue?: string; required?: boolean; allowEmpty?: boolean }) { return <div className="grid gap-2 py-3 sm:grid-cols-[180px_1fr]"><span className="text-xs font-bold text-slate-500">{label}{required && <Required/>}</span><div className="flex flex-wrap gap-4">{allowEmpty && <Radio name={name} value="" label="未選択" checked/>}{options.map((item, index) => <Radio key={item} name={name} value={item} label={item} checked={!allowEmpty && (defaultValue ? item === defaultValue : index === 0)}/>)}</div></div>; }
function Checks({ label, name, options, required }: { label: string; name: string; options: string[]; required?: boolean }) { return <fieldset className="grid gap-2 py-3 sm:grid-cols-[180px_1fr]"><legend className="text-xs font-bold text-slate-500">{label}{required && <Required/>}</legend><div className="flex flex-wrap gap-4">{options.map((item) => <label key={item} className="inline-flex items-center gap-2 text-sm"><input type="checkbox" name={name} value={item} className="size-4 accent-amber-500"/>{item}</label>)}</div></fieldset>; }
function Radio({ name, value, label, checked }: { name: string; value: string; label: string; checked?: boolean }) { return <label className="inline-flex items-center gap-2 text-sm"><input type="radio" name={name} value={value} defaultChecked={checked} className="size-4 accent-amber-500"/>{label}</label>; }
function MemberSelect({ name, label, members, defaultValue, required, extraOptions = [] }: { name: string; label: string; members: Member[]; defaultValue?: string; required?: boolean; extraOptions?: Member[] }) { return <label className="text-xs font-bold text-slate-500">{label}{required && <Required/>}<select name={name} defaultValue={defaultValue ?? ""} required={required} className={input}><option value="">選択してください</option>{members.map((member) => <option key={member.id} value={member.id}>{member.name}</option>)}{extraOptions.map((item) => <option key={item.id} value={`special:${item.id}`}>{item.name}</option>)}</select></label>; }
function MemberChecks({ name, label, members }: { name: string; label: string; members: Member[] }) { const [selected, setSelected] = useState<string[]>([]); return <fieldset className="sm:col-span-2"><legend className="text-xs font-bold text-slate-500">{label}</legend><details className="group relative mt-1.5"><summary className="flex h-11 cursor-pointer list-none items-center justify-between rounded-xl border border-slate-200 bg-white px-3 text-sm font-normal marker:content-none hover:border-amber-400"><span className={selected.length ? "text-slate-800" : "text-slate-400"}>{selected.length ? `${selected.length}名選択中` : "選択してください（複数選択可）"}</span><span aria-hidden className="text-xs text-slate-400 transition group-open:rotate-180">▼</span></summary><div className="absolute z-20 mt-1 grid max-h-64 w-full gap-1 overflow-y-auto rounded-xl border border-slate-200 bg-white p-2 shadow-xl sm:grid-cols-2 lg:grid-cols-3">{members.map((member) => <label key={member.id} className="inline-flex cursor-pointer items-center gap-2 rounded-lg px-2.5 py-2 text-sm hover:bg-amber-50"><input type="checkbox" name={name} value={member.id} checked={selected.includes(member.id)} onChange={(event) => setSelected((current) => event.target.checked ? [...current, member.id] : current.filter((id) => id !== member.id))} className="size-4 accent-amber-500"/>{member.name}</label>)}</div></details></fieldset>; }
function TimeRange({ start, end }: { start: string; end: string }) { return <div><span className="text-xs font-bold text-slate-500">活動時間<Required/></span><div className="mt-1.5 flex items-center gap-2"><input type="time" name="startTime" step={900} defaultValue={start} required className={input.replace("mt-1.5 ", "")}/><span>〜</span><input type="time" name="endTime" step={900} defaultValue={end} required className={input.replace("mt-1.5 ", "")}/></div></div>; }
function MonthFields() { return <div><span className="text-xs font-bold text-slate-500">受注予定月</span><div className="mt-1.5 grid grid-cols-2 gap-2"><select name="expectedOrderYear" className={input.replace("mt-1.5 ", "")}><option value="">年</option>{Array.from({ length: 28 }, (_, index) => 2009 + index).map((year) => <option key={year} value={year}>{year}年</option>)}</select><select name="expectedOrderMonth" className={input.replace("mt-1.5 ", "")}><option value="">月</option>{Array.from({ length: 12 }, (_, index) => String(index + 1).padStart(2, "0")).map((month) => <option key={month} value={month}>{month}月</option>)}</select></div></div>; }

type ProductRow = { id: number; name: string; amount: string; quantity: string };
function ProductEditor({ initialProduct, status, showQuantity }: { initialProduct: string; status: string; showQuantity: boolean }) {
  const [rows, setRows] = useState<ProductRow[]>([{ id: 1, name: productOptions.includes(initialProduct as typeof productOptions[number]) ? initialProduct : "商材未定", amount: "", quantity: "" }]);
  const [mainId, setMainId] = useState(1);
  const [perProduct, setPerProduct] = useState(false);
  const update = (id: number, values: Partial<ProductRow>) => setRows((current) => current.map((row) => row.id === id ? { ...row, ...values } : row));
  const mainProduct = rows.find((row) => row.id === mainId)?.name ?? rows[0]?.name ?? "";
  const totalAmount = perProduct ? rows.reduce((sum, row) => sum + Number(row.amount || 0), 0) : 0;
  const totalQuantity = perProduct ? rows.reduce((sum, row) => sum + Number(row.quantity || 0), 0) : 0;
  return <div className="rounded-xl border border-slate-200 p-3"><input type="hidden" name="product" value={mainProduct}/><input type="hidden" name="productsJson" value={JSON.stringify(rows.map(({ name, amount, quantity }) => ({ name, amount, quantity, main: name === mainProduct })))}/><p className="text-xs font-bold text-slate-500">商材<Required/></p><div className="mt-2 space-y-2">{rows.map((row, index) => <div key={row.id} className="grid gap-2 sm:grid-cols-[auto_1fr_auto]"><label className="flex items-center gap-1 text-xs"><input type="radio" name="mainProductId" checked={mainId === row.id} onChange={() => setMainId(row.id)} className="accent-amber-500"/>{index === 0 ? "メイン" : "選択"}</label><select value={row.name} onChange={(event) => update(row.id, { name: event.target.value })} className={input.replace("mt-1.5 ", "")} required>{productOptions.map((item) => <option key={item}>{item}</option>)}</select><button type="button" disabled={rows.length === 1} onClick={() => { setRows((current) => current.filter((item) => item.id !== row.id)); if (mainId === row.id) setMainId(rows.find((item) => item.id !== row.id)?.id ?? 1); }} className="rounded-lg border px-3 text-sm disabled:opacity-30">－</button>{status === "受注" && perProduct && <div className="col-start-2 grid grid-cols-2 gap-2"><input aria-label={`${row.name}の受注額`} type="number" min={0} value={row.amount} onChange={(event) => update(row.id, { amount: event.target.value })} placeholder="受注額" required className={input.replace("mt-1.5 ", "")}/>{showQuantity && <input aria-label={`${row.name}の受注数量`} type="number" min={0} value={row.quantity} onChange={(event) => update(row.id, { quantity: event.target.value })} placeholder="数量" required className={input.replace("mt-1.5 ", "")}/>}</div>}</div>)}</div><button type="button" onClick={() => setRows((current) => [...current, { id: Math.max(...current.map((row) => row.id)) + 1, name: "商材未定", amount: "", quantity: "" }])} className="mt-2 rounded-lg border border-amber-300 px-3 py-2 text-xs font-bold text-amber-900">＋ 商材を追加</button>{status === "受注" && <div className="mt-4 border-t pt-3"><label className="inline-flex items-center gap-2 text-sm font-semibold"><input type="checkbox" checked={perProduct} onChange={(event) => setPerProduct(event.target.checked)} className="accent-amber-500"/>商材毎に入力する</label>{perProduct && <><input type="hidden" name="orderAmount" value={totalAmount}/><input type="hidden" name="orderQuantity" value={totalQuantity}/></>}{!perProduct && <div className="mt-3 grid gap-3 sm:grid-cols-2"><Field name="orderAmount" label="受注額（円）" type="number" required/>{showQuantity && <Field name="orderQuantity" label="受注数量" type="number" required/>}</div>}<div className="mt-3"><Field name="orderDate" label="受注日" type="date" required/></div>{perProduct && <p className="mt-2 text-xs font-bold text-slate-600">合計：{totalAmount.toLocaleString("ja-JP")}円{showQuantity ? `／${totalQuantity}個` : ""}</p>}</div>}</div>;
}

function AiDetailsArea({ initialDetails, aiSummary }: { initialDetails: string; aiSummary: string }) { const [details, setDetails] = useState(initialDetails); return <div><div className="flex items-center justify-between gap-3"><span className="text-xs font-bold text-slate-500">活動詳細</span>{aiSummary && <button type="button" onClick={() => setDetails((current) => current ? `${current}\n\n${aiSummary}` : aiSummary)} className="rounded-lg border border-amber-300 bg-amber-50 px-3 py-1.5 text-xs font-bold text-amber-900">AI要約を反映</button>}</div>{aiSummary && <p className="mt-2 rounded-lg bg-amber-50 p-3 text-xs leading-6 text-slate-600">AI要約：{aiSummary}</p>}<textarea name="details" rows={6} value={details} onChange={(event) => setDetails(event.target.value)} className="mt-1.5 w-full rounded-xl border border-slate-200 p-3 text-sm font-normal outline-none focus:border-amber-500"/></div>; }
