"use client";

import { useActionState } from "react";
import { CheckCircle2, LoaderCircle } from "lucide-react";
import { saveDetailedActivityReport, type DetailedReportState } from "@/app/activities/[id]/report/actions";
import { AudioAnalysisUpload } from "@/components/activities/audio-analysis-upload";

type Member = { id: string; name: string };
type Defaults = { date: string; startTime: string; endTime: string; product: string; ownerId: string; progressStep: string };
export function ActivityReportForm({ activityId, defaults, members }: { activityId: string; defaults: Defaults; members: Member[] }) {
  const [state, action, pending] = useActionState(saveDetailedActivityReport, {} as DetailedReportState);
  return <form action={action} className="space-y-5"><input type="hidden" name="id" value={activityId}/>
    <Section title="登録内容の選択"><div className="flex flex-wrap gap-5"><Radio name="registrationType" value="actual" label="活動実績を登録する（共通活動／個別活動）" checked/><Radio name="registrationType" value="planned" label="活動予定を登録する（活動予定のみ）"/></div></Section>
    <Section title="共通活動" description="活動の基本情報を登録します。"><Grid>
      <Select name="salesType" label="営業タイプ" options={["IT営業活動", "IT同行活動", "書類不備", "フォロー"]}/><Select name="salesProcess" label="営業プロセス" options={["IT営業活動", "IT同行活動"]}/><Select name="activityStatus" label="ステータス" options={["提案中", "受注", "失注", "保留中"]} placeholder="選択してください"/><Field name="activityDate" label="活動日" value={defaults.date} type="date"/>
      <Field name="product" label="商材" value={defaults.product}/><Field name="customerContact" label="面談者"/><Field name="attendees" label="同席者" placeholder="複数名は読点区切りで入力"/><Select name="confidence" label="確度" options={["A：高", "B：普通", "C：低", "D：未確定"]} defaultValue="B：普通"/>
      <div className="sm:col-span-2"><Field name="progressStep" label="進行工程" value={defaults.progressStep} placeholder="例：提案準備、実施中、確認待ち"/></div>
    </Grid><Rows>
      <Choice label="コラボ提案" name="collaborationProposal" options={["提案あり", "提案なし"]}/><Choice label="電気提案" name="electricityProposal" options={["提案あり", "提案なし"]}/><Choice label="商談変化" name="dealChange" options={["○", "△", "×"]}/><Checks label="提案商材" name="proposedProducts" options={["UTM", "スイッチ", "AP", "複合機", "電話機", "サーバー", "その他"]}/><Checks label="面談者" name="contactRoles" options={["決裁者", "準決裁者", "担当者"]}/><Choice label="AXCEL同時提案" name="axcelProposal" options={["あり", "なし", "加入済"]}/><Choice label="AXCEL提案内容" name="axcelProposalDetail" options={["DX＊きづな 訴求あり合意", "DX＊きづな 訴求あり・未合意", "DX＊きづな 訴求なし"]}/><Checks label="AXCELプレゼン内容" name="axcelPresentation" options={["5大資源ツール説明", "申込チェック説明あり", "申込チェック説明なし"]}/><Choice label="顧客属性" name="customerAttribute" options={["ユーザーAXCELなし", "新規", "ユーザーAXCELあり", "ユーザー（AXCEL解約履歴あり）"]}/>
    </Rows></Section>
    <Section title="個別活動報告" description="活動の付加情報を登録します。同一活動に対して複数人が個別登録できます。"><Grid>
      <div className="text-xs font-bold text-slate-500">活動担当者<div className="mt-1.5 flex h-11 items-center rounded-xl border border-slate-200 bg-slate-50 px-3 text-sm text-slate-800">{members.find((item) => item.id === defaults.ownerId)?.name ?? "ログイン中の担当者"}</div></div><TimeRange start={defaults.startTime} end={defaults.endTime}/><div className="sm:col-span-2"><Area name="details" label="活動詳細"/></div>
      <Choice label="訪問回数" name="visitCount" options={["初回訪問", "再訪問", "3回目", "4回目以降"]}/><Field name="appointmentOwner" label="アポ担当"/><Field name="fieldOwner" label="現場担当"/><Field name="companionOwner" label="同行担当"/><Select name="appointmentType" label="アポ内容" options={["新規アポ", "再訪アポ", "フォロー"]} placeholder="選択してください"/><Field name="negotiator" label="商談担当者"/><Field name="negotiatorTitle" label="商談担当者役職"/><Choice label="商談ステージ" name="dealStage" options={["アプローチ", "現状確認", "提案", "クロージング"]}/><Field name="vendor" label="販社"/><Field name="model" label="機種"/><Field name="proposedModel" label="提案機種"/><Field name="currentLeaseCompany" label="現在リース会社"/><Field name="leaseCompany" label="リース会社"/><Field name="currentLeaseFee" label="現在リース料金" type="number"/><Field name="proposedLeaseFee" label="提案リース料金" type="number"/><Field name="remainingLeasePayments" label="リース残回数" type="number"/><Select name="pricingSetting" label="料金設定" options={["料金UP", "料金維持", "料金DOWN"]} placeholder="選択してください"/>
    </Grid></Section>
    <Section title="AI商談分析" description="音声を選択するだけで、文字起こし・営業と顧客の識別・詳細分析を自動で行います。待たずに活動登録を完了できます。">
      <AudioAnalysisUpload activityId={activityId}/>
      <details className="rounded-xl border border-slate-200"><summary className="cursor-pointer px-4 py-3 text-xs font-bold text-slate-500">文字起こし済みテキストを使う場合</summary><div className="border-t p-4"><label className="block text-xs font-bold text-slate-500">商談・通話の文字起こし<textarea name="aiTranscript" rows={8} className="mt-1.5 w-full rounded-xl border border-slate-200 p-3 text-sm font-normal leading-7 outline-none focus:border-amber-500"/></label></div></details>
    </Section>
    {state.message && !state.success && <p className="rounded-lg bg-red-50 p-3 text-sm text-red-700">{state.message}</p>}{state.success && <p className="flex items-center gap-2 rounded-lg bg-emerald-50 p-3 text-sm font-semibold text-emerald-700"><CheckCircle2 size={18}/>活動内容を保存しました。</p>}
    <div className="flex justify-end border-t border-slate-200 pt-5"><button disabled={pending || state.success} className="flex min-w-40 items-center justify-center gap-2 rounded-xl bg-[#f2c94c] px-5 py-3 text-sm font-bold text-slate-900 disabled:opacity-50">{pending && <LoaderCircle size={18} className="animate-spin"/>}{pending ? "保存中" : "活動を登録する"}</button></div>
  </form>;
}
const input = "mt-1.5 h-11 w-full rounded-xl border border-slate-200 bg-white px-3 text-sm font-normal outline-none focus:border-amber-500";
function Section({ title, description, children }: { title: string; description?: string; children: React.ReactNode }) { return <section className="overflow-hidden rounded-xl border border-slate-200"><div className="border-b border-slate-200 bg-slate-50 px-4 py-3"><h2 className="text-sm font-bold">{title}</h2>{description && <p className="mt-1 text-xs text-slate-400">{description}</p>}</div><div className="space-y-5 p-4 md:p-5">{children}</div></section>; }
function Grid({ children }: { children: React.ReactNode }) { return <div className="grid gap-4 sm:grid-cols-2">{children}</div>; } function Rows({ children }: { children: React.ReactNode }) { return <div className="divide-y divide-slate-100">{children}</div>; }
function Field({ name, label, value, type = "text", placeholder }: { name: string; label: string; value?: string; type?: string; placeholder?: string }) { return <label className="text-xs font-bold text-slate-500">{label}<input name={name} type={type} min={type === "number" ? 0 : undefined} defaultValue={value} placeholder={placeholder} className={input}/></label>; }
function Area({ name, label }: { name: string; label: string }) { return <label className="text-xs font-bold text-slate-500">{label}<textarea name={name} rows={6} className="mt-1.5 w-full rounded-xl border border-slate-200 p-3 text-sm font-normal outline-none focus:border-amber-500"/></label>; }
function Select({ name, label, options, placeholder, defaultValue }: { name: string; label: string; options: string[]; placeholder?: string; defaultValue?: string }) { return <label className="text-xs font-bold text-slate-500">{label}<select name={name} defaultValue={defaultValue ?? ""} className={input}>{placeholder && <option value="">{placeholder}</option>}{options.map((item) => <option key={item}>{item}</option>)}</select></label>; }
function Choice({ label, name, options }: { label: string; name: string; options: string[] }) { return <div className="grid gap-2 py-3 sm:grid-cols-[180px_1fr]"><span className="text-xs font-bold text-slate-500">{label}</span><div className="flex flex-wrap gap-4">{options.map((item, index) => <Radio key={item} name={name} value={item} label={item} checked={index === 0}/>)}</div></div>; }
function Checks({ label, name, options }: { label: string; name: string; options: string[] }) { return <div className="grid gap-2 py-3 sm:grid-cols-[180px_1fr]"><span className="text-xs font-bold text-slate-500">{label}</span><div className="flex flex-wrap gap-4">{options.map((item) => <label key={item} className="inline-flex items-center gap-2 text-sm"><input type="checkbox" name={name} value={item} className="size-4 accent-amber-500"/>{item}</label>)}</div></div>; }
function Radio({ name, value, label, checked }: { name: string; value: string; label: string; checked?: boolean }) { return <label className="inline-flex items-center gap-2 text-sm"><input type="radio" name={name} value={value} defaultChecked={checked} className="size-4 accent-amber-500"/>{label}</label>; }
function TimeRange({ start, end }: { start: string; end: string }) { return <div><span className="text-xs font-bold text-slate-500">活動時間</span><div className="mt-1.5 flex items-center gap-2"><input type="time" name="startTime" defaultValue={start} className={input.replace("mt-1.5 ", "")}/><span>〜</span><input type="time" name="endTime" defaultValue={end} className={input.replace("mt-1.5 ", "")}/></div></div>; }
