import { ArrowLeft, BriefcaseBusiness, Building2, ClipboardList, MapPin, Phone, UsersRound } from "lucide-react";
import Link from "next/link";
import { notFound } from "next/navigation";
import { AppShell } from "@/components/layout/app-shell";
import { MasterOpportunityDialog } from "@/components/opportunities/master-opportunity-dialog";
import { requireAuth } from "@/lib/auth/require-auth";
import { activityStatusLabel, activityTypeLabel } from "@/domain/activities/labels";

type CustomerRow = { id: string; external_id: string; name: string; phone: string | null; postal_code: string | null; address: string | null; notes: string | null; registration_details: Record<string, unknown> | null; department_id: string | null; departments: { name: string } | { name: string }[] | null };
type OpportunityRow = { id: string; source_activity_id: string | null; name: string; product_name: string | null; customer_contact: string | null; sales_type: string | null; sales_process: string | null; progress_step: string | null; status: string; confidence: string; priority: string; team_visibility: string; notes: string | null; updated_at: string; employees: { name: string } | { name: string }[] | null };
type ActivityRow = { id: string; title: string; activity_type: string; starts_at: string; ends_at: string; status: string; result: string | null; common_report: Record<string, unknown> | null; schedule_details: Record<string, unknown> | null; employees: { name: string } | { name: string }[] | null };
type AnalysisRow = { activity_id: string; analysis: { summary?: unknown } | null };

export default async function CustomerPortalPage({ params, searchParams }: { params: Promise<{ id: string }>; searchParams: Promise<{ section?: string; opportunityId?: string; activityId?: string }> }) {
  const [{ id }, query, context] = await Promise.all([params, searchParams, requireAuth()]);
  const lookupColumn = /^[0-9a-f]{8}-[0-9a-f]{4}-[1-8][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i.test(id) ? "id" : "external_id";
  const customerQuery = context.db.from("customers").select("id,external_id,name,phone,postal_code,address,notes,registration_details,department_id,departments(name)").eq("organization_id", context.organizationId).eq(lookupColumn, id);
  const customerResult = await customerQuery.maybeSingle();
  let data = customerResult.data;
  if (customerResult.error?.code === "42703") {
    const fallbackQuery = context.db.from("customers").select("id,external_id,name,phone,postal_code,address,notes,department_id,departments(name)").eq("organization_id", context.organizationId).eq(lookupColumn, id);
    const fallback = await fallbackQuery.maybeSingle();
    data = fallback.data as typeof data;
  }
  if (!data) notFound();
  const customer = data as unknown as CustomerRow;
  let activityQuery = context.db.from("activities").select("id,title,activity_type,starts_at,ends_at,status,result,common_report,schedule_details,employee_id,department_id,employees(name)").eq("organization_id", context.organizationId).eq("customer_id", customer.id);
  let opportunityQuery = context.db.from("opportunities").select("id,source_activity_id,name,product_name,customer_contact,sales_type,sales_process,progress_step,status,confidence,priority,team_visibility,notes,updated_at,employee_id,department_id,employees(name)").eq("organization_id", context.organizationId).eq("customer_id", customer.id);
  if (context.role === "sales_rep") activityQuery = activityQuery.eq("employee_id", context.employeeId);
  if (context.role === "department_admin") activityQuery = activityQuery.in("department_id", context.departmentIds);
  if (context.role === "sales_rep") opportunityQuery = opportunityQuery.eq("employee_id", context.employeeId);
  if (context.role === "department_admin") opportunityQuery = opportunityQuery.in("department_id", context.departmentIds);
  const [{ data: activityRows }, { data: opportunityRows }, { data: productRows }] = await Promise.all([activityQuery.order("starts_at", { ascending: false }).limit(100), opportunityQuery.order("updated_at", { ascending: false }).limit(100), context.db.from("products").select("name").eq("organization_id", context.organizationId).eq("status", "active").order("name")]);
  const activities = (activityRows ?? []) as ActivityRow[];
  const { data: analysisRows } = activities.length ? await context.db.from("activity_ai_analyses").select("activity_id,analysis").eq("organization_id", context.organizationId).eq("status", "completed").in("activity_id", activities.map((item) => item.id)) : { data: [] };
  const analysisSummaries = new Map((analysisRows as AnalysisRow[] | null ?? []).flatMap((row) => typeof row.analysis?.summary === "string" && row.analysis.summary.trim() ? [[row.activity_id, row.analysis.summary] as const] : []));
  const opportunities = (opportunityRows ?? []) as unknown as OpportunityRow[];
  const requestedActivity = activities.find((item) => item.id === query.activityId);
  const requestedOpportunityId = query.opportunityId ?? (typeof requestedActivity?.schedule_details?.opportunityId === "string" ? requestedActivity.schedule_details.opportunityId : undefined);
  const selectedOpportunity = opportunities.find((item) => item.id === requestedOpportunityId) ?? opportunities[0];
  const showAllActivities = query.section === "activities" && !requestedOpportunityId;
  const opportunityActivities = showAllActivities ? activities : selectedOpportunity ? activities.filter((item) => item.id === selectedOpportunity.source_activity_id || item.schedule_details?.opportunityId === selectedOpportunity.id) : [];
  const selectedActivity = opportunityActivities.find((item) => item.id === query.activityId) ?? opportunityActivities[0];
  const details = customer.registration_details ?? {};
  const savedContacts = Array.isArray(details.contacts) ? details.contacts as { name?: string; department?: string; title?: string; role?: string }[] : [];
  const opportunityContacts = [...new Set(opportunities.map((item) => item.customer_contact).filter((value): value is string => Boolean(value)))].filter((name) => !savedContacts.some((item) => item.name === name)).map((name) => ({ name, department: undefined, title: undefined, role: "顧客担当" }));
  const contacts = [...savedContacts, ...opportunityContacts];
  const branchName = String(details.branchName || "本社");
  const branchKana = String(details.branchKana || "ホンシャ");

  return <AppShell active="/customers" displayName={context.displayName} department={context.departmentName}>
    <div className="mx-auto max-w-6xl p-4 pb-24 md:p-8">
      <Link href="/customers" className="mb-5 inline-flex items-center gap-2 text-sm font-semibold text-slate-500 hover:text-amber-800"><ArrowLeft size={17} />顧客一覧へ戻る</Link>
      <section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm md:p-6"><p className="text-xs font-bold text-amber-800">顧客情報</p><div className="mt-2 flex flex-wrap items-center gap-3"><h1 className="text-lg font-bold md:text-xl">{customer.name}</h1><span className="rounded-full bg-amber-50 px-3 py-1 text-xs font-bold text-amber-900">{branchName}（{branchKana}）</span></div><div className="mt-5 space-y-3 border-t border-slate-100 pt-5"><p className="flex items-start gap-3 text-sm text-slate-700"><MapPin size={18} className="mt-0.5 shrink-0 text-slate-400"/><span>{customer.postal_code && <span className="mr-3 text-slate-500">〒{formatPostalCode(customer.postal_code)}</span>}{customer.address ?? "住所未登録"}</span></p>{customer.phone && <p className="flex items-center gap-3 text-sm font-semibold text-slate-700"><Phone size={18} className="shrink-0 text-slate-400"/><a href={`tel:${customer.phone}`} className="hover:text-amber-800 hover:underline">{customer.phone}</a></p>}</div>{customer.notes && <p className="mt-5 rounded-xl bg-slate-50 p-4 text-sm leading-6 text-slate-600">{customer.notes}</p>}</section>

      <PortalSection icon={UsersRound} eyebrow="担当者情報" title="担当者一覧" count={contacts.length}><DataTable headers={["No.", "担当者名", "部署", "役職", "役割"]} empty="登録された顧客担当者はいません。">{contacts.map((contact, index) => <tr key={`${contact.name}-${index}`} className="border-t border-slate-100"><Cell>{index + 1}</Cell><Cell strong>{contact.name || "—"}</Cell><Cell>{contact.department || "—"}</Cell><Cell>{contact.title || "—"}</Cell><Cell>{contactRoleLabel(contact.role)}</Cell></tr>)}</DataTable></PortalSection>

      <PortalSection icon={BriefcaseBusiness} eyebrow="案件情報" title="案件履歴" count={opportunities.length} action={<MasterOpportunityDialog customers={[{ id: customer.id, name: customer.name }]} products={(productRows ?? []).map((item) => item.name)} defaultCustomerId={customer.id}/>}><SplitPanel list={<DataTable headers={["No.", "案件名", "商材名", "顧客担当", "営業担当", "最終活動日"]} empty="案件はまだ登録されていません。まずこの顧客の案件を作成してください。">{opportunities.map((opportunity, index) => <tr key={opportunity.id} className={`border-t border-slate-100 ${selectedOpportunity?.id === opportunity.id ? "bg-amber-50" : ""}`}><Cell>{index + 1}</Cell><Cell strong><Link href={portalHref(customer.external_id, { opportunityId: opportunity.id })} className="text-amber-900 hover:underline">{opportunity.name}</Link></Cell><Cell>{opportunity.product_name || "—"}</Cell><Cell>{opportunity.customer_contact || "—"}</Cell><Cell>{relation(opportunity.employees)?.name || "—"}</Cell><Cell>{formatDate(opportunity.updated_at)}</Cell></tr>)}</DataTable>} detail={selectedOpportunity ? <OpportunitySummary opportunity={selectedOpportunity}/> : <EmptyDetail text="案件を作成すると、ここに進捗が表示されます。"/>}/></PortalSection>

      <div id="activities" className="scroll-mt-4"><PortalSection icon={ClipboardList} eyebrow="日報" title="活動・日報履歴" count={opportunityActivities.length} action={selectedOpportunity ? <Link href={`/?customerId=${customer.id}&opportunityId=${selectedOpportunity.id}`} className="rounded-lg bg-[#f2c94c] px-3 py-2 text-xs font-bold">活動予定を登録</Link> : undefined}><SplitPanel list={<DataTable headers={["No.", "タイプ名", "プロセス", "ステータス", "確度", "優先順位", "最終活動日"]} empty={selectedOpportunity ? "日報はまだ登録されていません。活動予定を登録してください。" : "先に案件を作成してください。"}>{opportunityActivities.map((activity, index) => { const report = activity.common_report ?? {}; return <tr key={activity.id} className={`border-t border-slate-100 ${selectedActivity?.id === activity.id ? "bg-amber-50" : ""}`}><Cell>{index + 1}</Cell><Cell strong><Link href={portalHref(customer.external_id, { opportunityId: selectedOpportunity?.id, activityId: activity.id, section: query.section })} className="text-amber-900 hover:underline">{String(report.salesType || activityTypeLabel(activity.activity_type))}</Link></Cell><Cell>{String(report.salesProcess || "—")}</Cell><Cell>{String(report.activityStatus || activityStatusLabel(activity.status))}</Cell><Cell>{String(report.confidence || "—")}</Cell><Cell>{selectedOpportunity?.priority ? priorityLabel(selectedOpportunity.priority) : "—"}</Cell><Cell>{formatDate(activity.starts_at)}</Cell></tr>; })}</DataTable>} detail={selectedActivity ? <><ActivityDetail activity={selectedActivity} aiAnalysisSummary={analysisSummaries.get(selectedActivity.id)}/><Link href={`/activities/${selectedActivity.id}/report`} className="mt-4 inline-flex w-full items-center justify-center rounded-lg bg-slate-900 px-4 py-2.5 text-sm font-bold text-white">日報を登録・編集</Link></> : <EmptyDetail text={selectedOpportunity ? "活動予定を作成すると、ここから日報を登録できます。" : "顧客の案件を先に作成してください。"}/>}/></PortalSection></div>

    </div>
  </AppShell>;
}

function PortalSection({ icon: Icon, eyebrow, count, action, children }: { icon: typeof Building2; eyebrow: string; title: string; count: number; action?: React.ReactNode; children: React.ReactNode }) { const heading = eyebrow === "日報" ? "活動情報" : eyebrow; return <section className="mt-6 overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><header className="flex flex-wrap items-center gap-3 border-b border-slate-200 px-5 py-4"><span className="grid size-9 place-items-center rounded-lg bg-amber-50 text-amber-800"><Icon size={18}/></span><h2 className="font-bold">{heading}</h2><span className="rounded-full bg-slate-100 px-2.5 py-1 text-xs font-bold text-slate-600">{count}件</span>{action && <div className="ml-auto">{action}</div>}</header><div className="p-5">{children}</div></section>; }
function SplitPanel({ list, detail }: { list: React.ReactNode; detail: React.ReactNode }) { return <div className="grid gap-4 xl:grid-cols-[minmax(0,1.7fr)_minmax(280px,0.8fr)]"><div className="overflow-x-auto overscroll-x-contain">{list}</div><aside className="rounded-xl border border-amber-200 bg-amber-50/40 p-4">{detail}</aside></div>; }
function DataTable({ headers, empty, children }: { headers: string[]; empty: string; children: React.ReactNode }) { const hasRows = Array.isArray(children) ? children.length > 0 : Boolean(children); return <table className="w-full min-w-[760px] text-left text-sm"><thead className="bg-slate-900 text-xs text-white"><tr>{headers.map((header) => <th key={header} className="whitespace-nowrap px-3 py-3">{header}</th>)}</tr></thead><tbody>{hasRows ? children : <tr><td colSpan={headers.length} className="py-12 text-center text-slate-400">{empty}</td></tr>}</tbody></table>; }
function Cell({ children, strong }: { children: React.ReactNode; strong?: boolean }) { return <td className={`whitespace-nowrap px-3 py-3 ${strong ? "font-bold" : "text-slate-600"}`}>{children}</td>; }
function DetailList({ title, rows }: { title: string; rows: Array<[string, unknown]> }) { return <><h3 className="font-bold">{title}</h3><dl className="mt-3 divide-y divide-amber-100">{rows.filter(([, value]) => value !== null && value !== undefined && value !== "").map(([label, value]) => <div key={label} className="py-2"><dt className="text-xs font-bold text-amber-800">{label}</dt><dd className="mt-0.5 whitespace-pre-wrap text-sm">{String(value)}</dd></div>)}</dl></>; }
function OpportunitySummary({ opportunity }: { opportunity: OpportunityRow }) { return <><h3 className="font-bold">{opportunity.product_name || opportunity.name}</h3><div className="mt-3 flex flex-wrap gap-2 text-xs font-bold"><span className="rounded-full bg-white px-2.5 py-1 text-amber-900">{opportunity.sales_type || "営業タイプ未設定"}</span><span className="rounded-full bg-white px-2.5 py-1 text-amber-900">{opportunity.sales_process || "プロセス未設定"}</span><span className="rounded-full bg-slate-900 px-2.5 py-1 text-white">{opportunityStatusLabel(opportunity.status)}</span></div><dl className="mt-3 divide-y divide-amber-100">{[["顧客担当", opportunity.customer_contact], ["営業担当", relation(opportunity.employees)?.name], ["案件状態", opportunityStatusLabel(opportunity.status)], ["他チームへの案件公開", opportunity.team_visibility === "private" ? "非公開" : "公開"], ["備考", opportunity.notes]].map(([label, value]) => <div key={String(label)} className="py-2"><dt className="text-xs font-bold text-amber-800">{label}</dt><dd className="mt-0.5 whitespace-pre-wrap text-sm">{value ? String(value) : "—"}</dd></div>)}</dl><Link href={`/opportunities/${opportunity.id}`} className="mt-4 inline-flex w-full items-center justify-center rounded-lg bg-slate-900 px-4 py-2.5 text-sm font-bold text-white">詳細内容を表示する</Link></>; }
function ActivityDetail({ activity, aiAnalysisSummary }: { activity: ActivityRow; aiAnalysisSummary?: string }) { const report = activity.common_report ?? {}; return <DetailList title={formatDate(activity.starts_at)} rows={[["タイプ名", report.salesType || activityTypeLabel(activity.activity_type)], ["プロセス", report.salesProcess], ["ステータス", report.activityStatus || activityStatusLabel(activity.status)], ["確度", report.confidence], ["面談者", report.customerContact], ["同席者", Array.isArray(report.attendees) ? report.attendees.join("、") : report.attendees], ["コラボ提案", report.collaborationProposal], ["電気提案", report.electricityProposal], ["商談変化", report.dealChange], ["提案商材", Array.isArray(report.proposedProducts) ? report.proposedProducts.join("、") : report.proposedProducts], ["AXCEL同時提案", report.axcelProposal], ["AXCEL提案内容", report.axcelProposalDetail], ["顧客属性", report.customerAttribute], ["活動結果", activity.result], ["AI分析の要約", aiAnalysisSummary]]}/>; }
function EmptyDetail({ text }: { text: string }) { return <p className="grid min-h-32 place-items-center text-center text-sm text-slate-400">{text}</p>; }
function formatDate(value: string) { return new Intl.DateTimeFormat("ja-JP", { timeZone: "Asia/Tokyo", year: "numeric", month: "long", day: "numeric" }).format(new Date(value)); }
function formatPostalCode(value: string) { const digits = value.replace(/\D/g, ""); return digits.length === 7 ? `${digits.slice(0, 3)}-${digits.slice(3)}` : value; }
function relation<T>(value: T | T[] | null) { return Array.isArray(value) ? value[0] : value; }
function portalHref(customerId: string, values: { opportunityId?: string; activityId?: string; section?: string }) { const params = new URLSearchParams(); if (values.section) params.set("section", values.section); if (values.opportunityId) params.set("opportunityId", values.opportunityId); if (values.activityId) params.set("activityId", values.activityId); return `/customers/${customerId}?${params}${values.section === "activities" ? "#activities" : ""}`; }
function opportunityStatusLabel(value: string) { return ({ open: "進行中", won: "受注", lost: "失注", on_hold: "保留中" } as Record<string, string>)[value] ?? value; }
function priorityLabel(value: string) { return ({ high: "高", medium: "中", low: "低" } as Record<string, string>)[value] ?? value; }
function contactRoleLabel(value?: string) { return ({ contact: "窓口", decision_maker: "決裁者", key_person: "キーマン", other: "その他", unknown: "不明", "顧客担当": "顧客担当" } as Record<string, string>)[value ?? ""] ?? value ?? "顧客担当"; }
