import Link from "next/link";
import { addMonthlyPickup, removeMonthlyPickup } from "@/app/pickups/actions";
import { AddScheduleDialog } from "@/components/activities/add-schedule-dialog";

export type MonthlyPickupItem = { id: string; departmentId: string; departmentName: string; employeeName: string; customerId: string; customerExternalId?: string | null; customerName: string; customerPhone: string | null; customerAddress: string | null; reason?: string | null; plannedDates: string[]; visitedDates: string[]; hasReport: boolean };

export function MonthlyPickupPanel({ month, items, customers, departments, canEdit, filters }: { month: string; items: MonthlyPickupItem[]; customers: { id: string; name: string }[]; departments: { id: string; name: string }[]; canEdit: boolean; filters?: { year: number; month: number; departments: { id: string; name: string }[]; members: { id: string; name: string }[]; departmentId: string; employeeId: string } }) {
  return <div>
    {filters && <form className="flex flex-wrap items-end gap-x-6 gap-y-3 border-b border-slate-100 bg-slate-50/70 px-5 py-4 text-xs">
      <input type="hidden" name="infoTab" value="pickups"/>
      <label className="flex items-center gap-2 font-semibold">表示範囲<select name="pickupYear" defaultValue={filters.year} className="rounded-lg border border-slate-200 bg-white px-2 py-2 font-normal">{Array.from({ length: 28 }, (_, index) => 2009 + index).map((value) => <option key={value} value={value}>{value}</option>)}</select><span>年</span><select name="pickupMonth" defaultValue={filters.month} className="rounded-lg border border-slate-200 bg-white px-2 py-2 font-normal">{Array.from({ length: 12 }, (_, index) => index + 1).map((value) => <option key={value} value={value}>{String(value).padStart(2, "0")}</option>)}</select><span>月</span></label>
      <label className="flex items-center gap-2 font-semibold">集計対象<select name="pickupDepartmentId" defaultValue={filters.departmentId} className="min-w-36 rounded-lg border border-slate-200 bg-white px-2 py-2 font-normal"><option value="">全部署</option>{filters.departments.map((department) => <option key={department.id} value={department.id}>{department.name}</option>)}</select><select name="pickupEmployeeId" defaultValue={filters.employeeId} className="min-w-36 rounded-lg border border-slate-200 bg-white px-2 py-2 font-normal"><option value="">全メンバー</option>{filters.members.map((member) => <option key={member.id} value={member.id}>{member.name}</option>)}</select></label>
      <button className="rounded-lg bg-[#f2c94c] px-4 py-2 font-bold text-slate-900">表示する</button>
    </form>}
    {canEdit && <form action={addMonthlyPickup} className="grid gap-3 border-b border-amber-100 bg-amber-50/50 px-5 py-4 md:grid-cols-[minmax(220px,1fr)_minmax(260px,2fr)_auto]">
      <input type="hidden" name="targetMonth" value={month}/>
      <label className="text-xs font-bold text-slate-600">今月ピックアップする顧客<select required name="customerId" defaultValue="" className="mt-1.5 h-11 w-full rounded-lg border border-slate-200 bg-white px-3 text-sm"><option value="" disabled>顧客を選択</option>{customers.map((customer) => <option key={customer.id} value={customer.id}>{customer.name}</option>)}</select></label>
      <label className="text-xs font-bold text-slate-600">ピックアップ理由<input name="reason" maxLength={500} placeholder="今月訪問する理由・確認したいこと" className="mt-1.5 h-11 w-full rounded-lg border border-slate-200 bg-white px-3 text-sm"/></label>
      <button className="self-end rounded-lg bg-[#f2c94c] px-5 py-3 text-sm font-bold text-slate-900">追加する</button>
    </form>}
    <div className="max-h-[520px] overflow-auto"><table className="w-full min-w-[1150px] text-left text-sm"><thead className="sticky top-0 z-[1] bg-slate-50 text-xs text-slate-500"><tr><th className="px-4 py-3">部署</th><th className="px-4 py-3">担当者</th><th className="px-4 py-3">顧客名</th><th className="px-4 py-3">ピックアップ理由</th><th className="px-4 py-3">訪問予定</th><th className="px-4 py-3">訪問実績</th><th className="px-4 py-3">日報</th><th className="px-4 py-3">状態</th>{canEdit && <th className="px-4 py-3 text-right">操作</th>}</tr></thead><tbody>
      {items.map((item) => { const status = item.hasReport ? "日報済み" : item.visitedDates.length ? "訪問済み" : item.plannedDates.length ? "予定済み" : "未予定"; return <tr key={item.id} className="border-t border-slate-100"><td className="px-4 py-3">{item.departmentName}</td><td className="px-4 py-3 font-semibold">{item.employeeName}</td><td className="px-4 py-3 font-semibold"><Link href={`/customers/${item.customerExternalId ?? item.customerId}`} className="hover:text-amber-800 hover:underline">{item.customerName}</Link></td><td className="max-w-sm whitespace-pre-wrap px-4 py-3 text-slate-600">{item.reason || "—"}</td><td className="px-4 py-3">{item.plannedDates.join("、") || "—"}</td><td className="px-4 py-3">{item.visitedDates.join("、") || "—"}</td><td className="px-4 py-3">{item.hasReport ? <span className="font-bold text-emerald-700">登録済み</span> : <span className="text-slate-400">未登録</span>}</td><td className="px-4 py-3"><span className={`rounded-full px-2.5 py-1 text-xs font-bold ${item.hasReport ? "bg-emerald-50 text-emerald-700" : item.visitedDates.length ? "bg-sky-50 text-sky-700" : item.plannedDates.length ? "bg-amber-100 text-amber-900" : "bg-red-50 text-red-700"}`}>{status}</span></td>{canEdit && <td className="px-4 py-3"><div className="flex items-center justify-end gap-3"><AddScheduleDialog departments={departments} defaultDate={pickupDefaultDate(month)} trigger="pickup" defaultCustomer={{ id: item.customerId, name: item.customerName, phone: item.customerPhone, address: item.customerAddress, departmentId: item.departmentId }}/><form action={removeMonthlyPickup}><input type="hidden" name="id" value={item.id}/><button className="text-xs font-bold text-red-600">解除</button></form></div></td>}</tr>; })}
      {!items.length && <tr><td colSpan={canEdit ? 9 : 8} className="px-5 py-14 text-center text-slate-400">{month.replace("-", "年")}月のピックアップ顧客はまだ登録されていません。</td></tr>}
    </tbody></table></div>
    <div className="border-t px-5 py-3 text-xs text-slate-500">{items.length}件</div>
  </div>;
}

function pickupDefaultDate(month: string) { const today = new Date().toLocaleDateString("sv-SE", { timeZone: "Asia/Tokyo" }); return today.startsWith(`${month}-`) ? today : `${month}-01`; }
